# Basic Python Practice
This notebook contains basic Python practice examples as part of my AI learning path.

Topics covered:
- Conditional statements
- Loops
- Sets


## Conditional Statements
Examples using if / elif / else.

## Loops
Examples using for loops and range.

## Collections – Sets
Basic usage of Python sets and iteration.

In [ ]:
score=80
if(score>90):
  print ("A")
elif 70<score<=90:
  print ("B")
else:
    print ("C")

In [ ]:
for i in range(1,5):
  print (i)

In [ ]:
fruits={"apple","Banana","Tomato"}
for fruit in fruits :
  print(fruit)


In [ ]:
for i in range(10):
  print (i)

In [ ]:
names={"Roaa","Reem","Rama","Leen"}
for name in names :
    print (name)

**List**


In [ ]:
numbers=[1,2,3,4,5]
numbers.append(6)
numbers[0]=40
print(numbers)
print(numbers[0])
print (len(numbers))
numbers.remove(6)
print (numbers)

In [ ]:
colors=["red","green","blue"]
colors.append("yellow")
colors[1]="blue"
print (len(colors))
colors.remove("blue")
print(colors)

In [ ]:
colors = ["red", "blue", "green", "blue", "yellow", "blue"]

for color in colors:
    if(color =="blue"):
        colors.remove("blue")
print (colors)

In [ ]:
numbers=[1,2,3,4,5]
for i in range(len(numbers)):
     numbers[i] = numbers[i] ** 2
print (numbers)

In [ ]:
numbers = [1, 2, 3, 4, 5]
seq=[x**2 for x in numbers]
print(seq)

In [ ]:
numbers = [1, 2, 3, 4, 5]
numbers=[x**2 for x in numbers]
print(numbers)

**List Comprehension**

In [ ]:
colors = ["red", "blue", "green", "blue", "yellow", "blue"]
new_colors=[color for color in colors if color !="blue"]
print(new_colors)

In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10]
even_numbers=[num for num in numbers if num%2==0]
print(even_numbers)

In [ ]:
words = ["apple","banana","kiwi"]
upper_Words=[word.upper() for word in words]
print(upper_Words)

In [ ]:
def greet():
    print("Hello Roaa!!")

greet()

In [ ]:
def greet(name):
    print(f"Hello {name}")

greet("Roaa")
greet(5)

In [ ]:
def add(a,b):
    return a+b
print(add(5,1))

In [ ]:
def square (number):
    return number**2
print(square(5))

In [ ]:
def is_even (num):
    return num%2==0
print(is_even(17))

In [ ]:
nums=[1,2,3,4,5]
for num in nums:
    print(square(num))

In [ ]:
nums=[1,2,3,4,5]
for num in nums:
    print(is_even(num))

In [ ]:
numbers = [1, 2, 3, 4, 5, 6]
result=["Evern" if num%2==0 else "odd" for num in numbers]
print (result)

In [ ]:
scores = [95, 60, 82, 40]
grades = [ "A" if grade>=90 else "B"if 80=>grade<=70 else "C" for grade in scores]
print (grades)

In [ ]:
nums = [3, 10, 11, 25, 7, 15]
result=["Big" if num>10 else "Small" for num in nums ]
print (result)

In [ ]:
nums = [2, 5, 8, 12, 15, 20, 3, 7]
result=["Big" if num>10 else "Even" if num%2==0 else "Odd" for num in nums if num>0 ]

print (result)

['Even', 'Odd', 'Even', 'Big', 'Big', 'Big', 'Odd', 'Odd']


Ternary **operator**

In [ ]:
age=18
result ="Adult" if age>=18 else "Not"
print (result)

In [ ]:
import numpy as np

arr=np.array([10,20,30,40,50])
print (arr+5)
print (arr[arr>25])

[15 25 35 45 55]
[30 40 50]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print (arr)
print (arr+10)
print (arr*2)
print (arr**2)
print (arr[arr>3])

[1 2 3 4 5]
[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[4 5]


In [ ]:
scores = [95, 67, 82, 45, 70, 88, 10]
names = ["Roaa", "Reem", "Rama", "Leen", "Sara", "Mona", "Lina"]

grades=["A"if g>=90 else "B" if 89 >= g>=70 else "C" for g in scores]
print (grades)

['A', 'C', 'B', 'C', 'B', 'B', 'C']


In [ ]:
scores = [95, 67, 82, 45, 70, 88, 10]

def is_passing(score):
    return score>=50


passing=[ is_passing(score) for score in scores]
print(passing)

[True, True, True, False, True, True, False]


In [ ]:
import numpy as np
scores = [95, 67, 82, 45, 70, 88, 10]

arr_scores=np.array([95, 67, 82, 45, 70, 88, 10])
print(arr_scores+5)



[100  72  87  50  75  93  15]


SET ...

In [ ]:
s={1,4,3}
print (s)
print(1 in s)

{1, 3, 4}
True


In [ ]:
emails = ["a@gmail", "b@gmail", "a@gmail"]
sSet=set(emails)
print (sSet)

{'b@gmail', 'a@gmail'}


In [ ]:
s={1,2,2,3}
f={4,4,5,6}
result = s.union(f)
print (result)

{1, 2, 3, 4, 5, 6}


In [ ]:
s={"hi",5,True,4.5}
print (s)

{True, 4.5, 5, 'hi'}


In [ ]:
print(hash("Roaa"))
print(hash("Roaa"))
print(hash("Mona"))
print(hash(4))
print(hash(1))

6703858797086421821
6703858797086421821
-7445089834023843634
4
1


**Tuple**

In [ ]:
t=(1,1,20,3,50)
print(t)
print(t[2])
for n in t :
    print (n)

print(f" lenght is : {len(t)}")
print(f" count is : {t.count(1)}")
print(f" index of element 20 is : {t.index(20)}")
print(f" slicing : {t[1:3]}")
t = (1, 2) * 3   # (1,2,1,2,1,2)
print(t)

(1, 1, 20, 3, 50)
20
1
1
20
3
50
 lenght is : 5
 count is : 2
 index of element 20 is : 2
 slicing : (1, 20)
(1, 2, 1, 2, 1, 2)


**Dictionary**